create table if not exists public.agradecimientos (
  id bigint generated by default as identity primary key,
  nombre text not null check (char_length(trim(nombre)) between 1 and 80),
  mensaje text not null check (char_length(trim(mensaje)) between 10 and 600),
  ciudad text check (ciudad is null or char_length(trim(ciudad)) <= 60),
  email text check (email is null or char_length(trim(email)) <= 120),
  aprobado boolean not null default true,
  destacado boolean not null default false,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists agradecimientos_public_feed_idx
  on public.agradecimientos (aprobado, destacado, created_at desc);

alter table public.agradecimientos
  alter column aprobado set default true;

update public.agradecimientos
  set aprobado = true
  where aprobado = false;

alter table public.agradecimientos enable row level security;

drop policy if exists "Public can read approved agradecimientos" on public.agradecimientos;
create policy "Public can read approved agradecimientos"
  on public.agradecimientos
  for select
  to anon, authenticated
  using (aprobado = true);

drop policy if exists "Public can submit agradecimientos" on public.agradecimientos;
create policy "Public can submit agradecimientos"
  on public.agradecimientos
  for insert
  to anon, authenticated
  with check (
    destacado = false
  );
